steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/label', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/label']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'label'
    - '--image'
    - 'gcr.io/$PROJECT_ID/label'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'CLOUD_RUN_ENV=1'
    - '--set-secrets'
    - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'

timeout: 1800s