OPENAI_API_KEY = "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"
LABEL_EMAIL = "label@alt-g.jp"
LABEL_PASSWORD = "KbWHq8jR"